dockerfiles_task:
  skip: $CIRRUS_BRANCH =~ '.*\.tmp'
  container:
    image: ellerbrock/alpine-bash-git

  script:
    - ./.ci/dockerfiles/generate.sh
    - git diff --exit-code


docs_task:
  skip: $CIRRUS_BRANCH =~ '.*\.tmp'
  container:
    dockerfile: .ci/dockerfiles/docs

  install_script: pip install -e .
  script: make -C docs/ html


Linux_task:
  skip: $CIRRUS_BRANCH =~ '.*\.tmp'
  allow_failures: $CIRRUS_TASK_NAME =~ '.*-rc-.*'
  container:
    matrix:
      - dockerfile: .ci/dockerfiles/python_3.6-slim
      - dockerfile: .ci/dockerfiles/python_3.7-slim
      - dockerfile: .ci/dockerfiles/python_3.8-rc-slim
      - dockerfile: .ci/dockerfiles/pypy_3.6-slim

  script:
    - command -v pypy3 >/dev/null && export PY=pypy3
    - ${PY-python3} --version
    - pip list
    - pytest

macOS_task:
  skip: $CIRRUS_BRANCH =~ '.*\.tmp'
  osx_instance:
    image: mojave-base
  env:
    PATH: ${HOME}/.pyenv/shims:${PATH}
    matrix:
      - PYTHON: 3.6.8
      - PYTHON: 3.7.2
  install_script:
    # Per the pyenv homebrew recommendations.
    # https://github.com/pyenv/pyenv/wiki#suggested-build-environment
    - sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /
    - brew install openssl readline pyenv
    - pyenv install ${PYTHON}
    - pyenv global ${PYTHON}
    - pyenv rehash
    - pip install --upgrade-strategy eager -U -r requirements-tests.txt
    - pip install -e .

  script:
    - python3 --version
    - pip list
    - pytest

Windows_task:
  skip: $CIRRUS_BRANCH =~ '.*\.tmp'
  allow_failures: $CIRRUS_TASK_NAME =~ '.*-rc-.*'
  windows_container:
    os_version: 2019
    matrix:
      - dockerfile: .ci/dockerfiles/python_3.6-windowsservercore-1809
      - dockerfile: .ci/dockerfiles/python_3.7-windowsservercore-1809

  script:
    - C:\Python\python.exe --version
    - C:\Python\python.exe -m pip list
    - C:\Python\python.exe -m pytest
