name: test

on:
  push:
  pull_request:
    branches: [ "canon" ]
  workflow_dispatch:

jobs:
  linux:
    strategy:
      matrix:
        image:
        - python:3.9
        - python:3.10
        - python:3.11
        - python:3.12
        - python:rc
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
      env:
        POETRY_VIRTUALENVS_IN_PROJECT: "true"
    steps:
      - uses: actions/checkout@v6
      - name: setup
        run: |
          python -m venv .venv
          .venv/bin/pip install -r requirements.txt -r requirements-tests.txt
      - name: run tests
        run: |
          .venv/bin/pytest --verbose
