name: test

on:
  push:
  pull_request:
    branches: [ "canon" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker.io/duckinator/bork
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-tags: true
          set-safe-directory: true
      - run: bork build
      - uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: ./dist

  linux:
    strategy:
      matrix:
        image:
        - python:3.9
        - python:3.10
        - python:3.11
        - python:3.12
        - python:rc
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
      env:
        POETRY_VIRTUALENVS_IN_PROJECT: "true"
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v4
        with:
          name: wheels
          path: ./dist
      - name: setup
        run: |
          python -m venv .venv
          .venv/bin/pip install dist/*.whl -r requirements.txt -r requirements-tests.txt
      - name: run tests
        run: |
          .venv/bin/pytest --verbose
